doctrine_cache:
    providers:

        elcodi_categories:
            type: redis
            namespace: categories

        elcodi_menus:
            type: redis
            namespace: menus

        elcodi_configurations:
            type: redis
            namespace: configuration

        elcodi_translations:
            type: redis
            namespace: translations
