parameters:

    #
    # Services
    #
    elcodi.template_loader.class: Elcodi\Bundle\BambooBundle\Services\TemplateLoader

    #
    # Commands
    #
    elcodi.template_loader_command.class: Elcodi\Bundle\BambooBundle\Command\TemplateLoaderCommand

    #
    # Twig extensions
    #
    elcodi.bamboo_api_metric_twig_extension.class: Elcodi\Bundle\BambooBundle\Twig\BambooAPIMetricExtension
