services:

    #
    # Page renderer
    #
    bamboo.page.renderer.template_renderer:
        class: Elcodi\Bundle\BambooBundle\Renderer\TemplatedPageRenderer
        arguments:
            - @templating.engine.twig
            - "Page:layout.html.twig"
            -
              - @=elcodi_config("store.template")
              - ElcodiBambooBundle

    #
    # Store tracker
    #
    elcodi.store_tracker:
        class: StdClass
        factory_service: elcodi.manager.configuration
        factory_method: get
        arguments: ['store.tracker']
