services:

    #
    # Page renderer
    #
    bamboo.page.renderer.template_renderer:
        class: Elcodi\Component\Page\Renderer\TemplatedPageRenderer
        arguments:
            - @templating.engine.twig
            - "Pages:page-static.html.twig"
            - @=elcodi_config("store.template")
            - ElcodiBambooBundle

    #
    # Store tracker
    #
    elcodi.store_tracker:
        class: StdClass
        factory_service: elcodi.manager.configuration
        factory_method: get
        arguments: ['store.tracker']
