services:

    #
    # Page renderer
    #
    bamboo.page.renderer.template_renderer:
        class: Elcodi\Bundle\BambooBundle\Renderer\TemplateRenderer
        arguments:
            - @templating.engine.twig

    #
    # Store tracker
    #
    elcodi.store_tracker:
        class: StdClass
        factory_service: elcodi.configuration_manager
        factory_method: get
        arguments: ['store.tracker']
