parameters:

    #
    # Mailers
    #
    elcodi.core.bamboo.mailer.customer_password_recover.class: Elcodi\Component\User\Mailer\PasswordRecoverMailer

services:

    elcodi.core.bamboo.mailer.customer_password_recover:
        class: %elcodi.core.bamboo.mailer.customer_password_recover.class%
        arguments:
            templating: @templating
            mailer: @mailer
            layout: %elcodi.core.bamboo.emails.customer_password_recover.layout%
            template: %elcodi.core.bamboo.emails.customer_password_recover.template%
            senderEmail: %elcodi.core.bamboo.emails.customer_password_recover.sender_email%
        tags:
            - { name: kernel.event_listener, event: password.recover, method: sendEmail }
