parameters:

    #
    # Mailers
    #
    elcodi.core.bamboo.mailer.customer_password_remember.class: Elcodi\Component\User\Mailer\PasswordRememberMailer

services:

    elcodi.core.bamboo.mailer.customer_password_remember:
        class: %elcodi.core.bamboo.mailer.customer_password_remember.class%
        arguments:
            templating: @templating
            mailer: @mailer
            layout: %elcodi.core.bamboo.emails.customer_password_remember.layout%
            template: %elcodi.core.bamboo.emails.customer_password_remember.template%
            senderEmail: %elcodi.core.bamboo.emails.customer_password_remember.sender_email%
        tags:
            - { name: kernel.event_listener, event: password.remember, method: sendEmail }
